filebeat.modules:
- module: nginx
  access: 
    enabled: true
    var.paths: ["/var/log/nginx/access.log*"]
    var.convert_timezone: true
  error:
    enabled: true
    var.paths: ["/var/log/nginx/error.log*"]
    var.convert_timezone: true
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  bulk_max_size: 20480
setup.dashboards.enabled: true
setup.kibana:
  host: "kibana:5601"
setup.template.settings:
 index:
   number_of_shards: 1
   codec: best_compression
setup.template.fields: "/usr/share/filebeat/fields.yml"
setup.template.overwrite: true