filebeat.modules:
- module: nginx
  access: 
    var.paths: ["/var/log/nginx/access.log*","/var/log/nginx/error.log*"]
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  bulk_max_size: 20480
  flush_interval: 5
setup.dashboards.enabled: true
setup.kibana:
  host: "kibana:5601"