filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/log-filebeat/statistic*.log
  encoding: utf-8
  fields:
      log_topic: test-log
  scan_frequency: 10s

output.kafka:
  enabled: true
  hosts: ["kafka:9092"]
  topic: '%{[fields.log_topic]}'